apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka-producer
  name: kafka-producer
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka-producer
    spec:
      containers:
      - image: producer:0.1
        name: producer
        resources: {}
status: {}
