apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest-proxy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-rest-proxy
  template:
    metadata:
      labels:
        app: kafka-rest-proxy
    spec:
      containers:
      - name: kafka-rest-proxy
        image: confluentinc/cp-kafka-rest:latest
        ports:
        - containerPort: 8082
        env:
        - name: KAFKA_REST_HOST_NAME
          value: "kafka-rest-proxy"
        - name: KAFKA_REST_LISTENERS
          value: "http://0.0.0.0:8082"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS
          value: "GET,POST,PUT,DELETE,OPTIONS"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://$(POD_IP):9092"

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-proxy-service
  namespace: demo
spec:
  selector:
    app: kafka-rest-proxy
  type: NodePort
  ports:
    - name: rest-proxy
      protocol: TCP
      port: 8082
      targetPort: 8082

