apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafka
    spec:
      containers:
      - image: confluentinc/confluent-local:7.6.1
        name: confluent-local-pod
        ports:
        - containerPort: 8082
        - containerPort: 9092
        - containerPort: 9093
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_REST_LISTENERS
          value: "http://0.0.0.0:8082"
        - name: KAFKA_REST_BOOTSTRAP_SERVERS
          value: "PLAINTEXT://localhost:9092"
        - name: KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS
          value: "GET,POST,PUT,DELETE,OPTIONS"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-service:9092"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-service.demo.svc.cluster.local:9093"
        - name: KAFKA_MAX_REQUEST_SIZE
          value: "200000000"
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "200000000"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "200000000"
        - name: ENABLE_SSL_CERTIFICATE_VERIFICATION
          value: "false"
        - name: KAFKA_CFG_MAX_REQUEST_SIZE
          value: "2097152"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "false"

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka-service
  namespace: demo
spec:
  ports:
  - name: "8082"
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: "90922"
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: "9093"
    port: 9093 
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
  type: NodePort
status:
  loadBalancer: {}
