apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: transactions
  name: transactions
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transactions
    spec:
      containers:
      - image: transactions:0.2
        name: transactions
        ports:
        - containerPort: 5000

--- 

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transactions
  name: transactions
  namespace: demo
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: transactions
  type: NodePort
