apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-conf
  namespace: demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9999']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: conf-prom
          configMap: 
            name: prom-conf
            defaultMode: 420
      containers:
      - image: prom/prometheus:v2.45.6
        name: prometheus-container
        volumeMounts:
          - name: conf-prom
            mountPath: /etc/prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: demo
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
      nodePort: 30999
  type: NodePort
