apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-conf
  namespace: demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9999']
    remote_write:
      - url: "http://thanos-sidecar.demo.svc:10901/api/v1/receive"

    remote_read:
      - url: "http://thanos-sidecar.demo.svc:10901/api/v1/read"
        required_matchers:
          job: "prometheus"
