apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-minio-config
  namespace: demo
data:
  minio.yaml: |
    type: S3
    config:
      bucket: "demotenant"
      endpoint: "http://demotenant-hl:9999"
      access_key: "$(THANOS_S3_ACCESS_KEY)"
      secret_key: "$(THANOS_S3_SECRET_KEY)"
      insecure: true

