apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      containers:
      - name: thanos-store
        image: quay.io/thanos/thanos:main-2024-06-25-d82b2bd
        args:
        - store
        - --objstore.config-file=/etc/thanos/minio.yaml
        - --http-address=0.0.0.0:10902
        - --grpc-address=0.0.0.0:10901
        volumeMounts:
        - name: thanos-config
          mountPath: /etc/thanos/minio.yaml
          subPath: minio.yaml
      volumes:
      - name: thanos-config
        configMap:
          name: thanos-minio-config
          items:
          - key: minio.yaml
            path: minio.yaml

