---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: docker.io/hostpath
    volume.kubernetes.io/storage-provisioner: docker.io/hostpath
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
  name: minio-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 190Gi
  storageClassName: hostpath
  volumeMode: Filesystem
  volumeName: minio-pv

---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  # This name uniquely identifies the Deployment
  name: minio
  namespace: demo
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      # Refer to the PVC created earlier
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: minio-pvc
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /storage
        env:
        - name: MINIO_ACCESS_KEY
          value: "minio"
        - name: MINIO_SECRET_KEY
          value: "minio123"
        - name: MINIO_ACCESS_KEY_FILE
          value: "minio"
        - name: MINIO_SECRET_KEY_FILE
          value: "minio"
        - name: MINIO_ROOT_USER_FILE
          value: "minio"
        - name: MINIO_ROOT_PASSWORD_FILE
          value: "minio"
        - name: MINIO_KMS_SECRET_KEY_FILE
          value: "minio"
        - name: MINIO_UPDATE_MINISIGN_PUBKEY
          value: "RWTx5Zr1tiHQLwG9keckT0c45M3AGeHD6IvimQHpyRywVWGbP1aVSGav"
        - name: MINIO_CONFIG_ENV_FILE
          value: "config.env"
        - name: MC_CONFIG_DIR
          value: "/tmp/.mc"
        ports:
        - containerPort: 9000
          hostPort: 9000
        - containerPort: 9001
          hostPort: 9001
        volumeMounts:
        - name: storage # must match the volume name, above
          mountPath: "/storage"
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30000  # Choose any available port in the range 30000-32767
  - name: "9001"
    port: 9001
    targetPort: 9001
    nodePort: 30001  # Choose any available port in the range 30000-32767
